### ISSUE TITLE
Function running out of memory

### ISSUE THREAD

**Issue by TravellingGuy** [ryanholland/rdslogs_to_s3#1]
Hi. I found your lambda function while looking for ways to export my RDS logs to S3. Thanks! It's somewhat working. :smile: 

I'm finding I'm running out of memory while it's running, especially during the initial run. I've set my lambda function to use 512MB of RAM and it will export some of the logs, then fail when it runs out of memory. I could keep increasing the memory available to the lambda function, but I think that will just delay the problem.

I'm wondering if you're not releasing memory after each log file gets copied to S3 or something like that. I'm not really a python developer, so I can only be limited help (at least initially). I'm going to dig into it and see if I can figure something out, but if you have an thoughts on reducing the memory usage that would be grand.

**Comment by TravellingGuy** [comment]
I actually have a workaround for this, that is to run the script outside of lambda the first time, then memory (and running time) are a non-issue.

**Comment by ryanholland** [comment]
@TravellingGuy Thanks for updating this, yes I think the first download if there is a large amount of logs in the system is what was causing the timeout/memory issue.
